### ISSUE TITLE
Text becomes unreadable on light themed consoles

### ISSUE THREAD

**Issue by MarioVilas** [rly0nheart/octosuite#1]
**Describe the bug**
Text is hard to read when the console background is not black.

**To Reproduce**
1. Open a console
2. Set any color scheme with a light background

**Expected behavior**
All text should be readable (even if it no longer looks pretty).

**Screenshots**
![Screenshot from 2022-04-13 15-45-30](https://user-images.githubusercontent.com/227923/163194916-b743afb6-bc30-4b66-b6d5-61fa57db056c.png)

For an example of a similarly colored tool:
![Screenshot from 2022-04-13 15-45-51](https://user-images.githubusercontent.com/227923/163194993-f4dd02da-4b95-4110-9f77-bfdbbe085792.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux, latest version

**Additional context**
A possible solution is never to specify black or white as text color, but rather use the default color, whichever it may be. Green or red colored text should always be visible anyway.

Another (complementary) solution would be to add an option to disable color altogether.

**Comment by rly0nheart** [comment]
Thanks, I mainly specified colors because my termux is dark themed. So in the next release, i'll either permanently disable all colors,  or have an option as you said to choose whether colors should be disabled or not. I'll close this issue as soon as I publish an update (which is what i'm currently working on).

**Comment by rly0nheart** [comment]
Hello @MarioVilas, the issue has been fixed in the latest (as of writing) v1.5.2-alpha.
Upon launch, users will be prompted to choose whether they would like to display colors or not.

**Prompt**
![Screenshot_20220414-024505](https://user-images.githubusercontent.com/74001397/163359458-926c1786-b077-4470-9330-971acb91b913.jpg)

**Colors disabled**
![Screenshot_20220414-024814](https://user-images.githubusercontent.com/74001397/163359596-b660f3c5-1eec-4a27-990a-952cbd5d5352.jpg)

**Colors enabled**
![Screenshot_20220414-024553](https://user-images.githubusercontent.com/74001397/163359786-11e13268-b564-46d6-8957-7374ce0a3f4c.jpg)
