### ISSUE TITLE
Version.tag

### ISSUE THREAD

**Issue by Sup3rY4k** [rly0nheart/octosuite#3]
I went to complete the installation and I got this error. I tried to play with it but I had no luck, Any help would be appreciated. 

Defaulting to user installation because normal site-packages is not writeable
WARNING: Requirement 'dist/octosuite-[version.tag]-py3-none-any.whl' looks like a filename, but the file does not exist
ERROR: Extras after version '==[version.tag]'

**Comment by rly0nheart** [comment]
Hello there @Sup3rY4k, could you use the issue template so that I can get more details about the error you're getting?

**Comment by Sup3rY4k** [comment]
@rly0nheart I went to install and receive this error. I tried replacing "version tag" with my version as well and it still gave me the same error. To reproduce, just follow the installation instructions. I am on desktop using kali 2022.2 
![error](https://user-images.githubusercontent.com/103078718/179097941-2aa5fee2-e07e-43b3-ae6d-aceef8dcfbe6.jpg)

**Comment by rly0nheart** [comment]
Ah I see, so the problem is, you're supposed to remove the *[version.tag]*, and write the current version tag of octosuite, just like in the screenshot below:
![Screenshot_20220715-003809](https://user-images.githubusercontent.com/74001397/179100228-d19af600-5708-4581-a138-86828ca63a6a.png)
 
Try doing this and let me know the outcome
